.checkov-scan:
  image: 
    name: $PIPELINE_COE_REGISTRY/checkov-container:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  # tags:
  #   - non_privileged
  #   - no_root
  #   - cstack
  variables:
    OPTS: "-d $WORKING_DIR --check $CHECKOV_IDS"
    WORKING_DIR: "."
    CHECKOV_IDS: "CKV_AWS_3,CKV_AWS_7,CKV_AWS_17,CKV_AWS_18,CKV_AWS_19,CKV_AWS_21,CKV_AWS_24,CKV_AWS_36,CKV_AWS_37,CKV_AWS_39,CKV_AWS_42,CKV_AWS_43,CKV_AWS_47,CKV_AWS_49,CKV_AWS_53,CKV_AWS_54,CKV_AWS_62,CKV_AWS_64,CKV_AWS_70,CKV_AWS_71,CKV_AWS_76,CKV_AWS_81,CKV_AWS_87,CKV_AWS_89,CKV_AWS_91,CKV_AWS_92,CKV_AWS_103,CKV_AWS_105,CKV_AWS_106,CKV_AWS_117,CKV_AWS_123,CKV_AWS_127,CKV_AWS_129,CKV_AWS_130,CKV_AWS_131,CKV_AWS_137,CKV_AWS_139,CKV_AWS_141,CKV_AWS_146,CKV_AWS_155,CKV_AWS_156,CKV_AWS_157,CKV_AWS_159,CKV_AWS_168,CKV_AWS_176,CKV_AWS_207,CKV_AWS_226,CKV_AWS_231,CKV_AWS_232,CKV_AWS_234,CKV_AWS_277,CKV2_AWS_8,CKV2_AWS_9,CKV2_AWS_10,CKV2_AWS_11,CKV2_AWS_12,CKV2_AWS_15,CKV2_AWS_18,CKV2_AWS_20,CKV2_AWS_28,CKV2_AWS_29,CKV_AZURE_15,CKV_AZURE_28,CKV_AZURE_29,CKV_AZURE_31,CKV_AZURE_44,CKV_AZURE_48,CKV_AZURE_53,CKV_AZURE_58,CKV_AZURE_60,CKV_AZURE_68,CKV_AZURE_70,CKV_AZURE_72,CKV_AZURE_78,CKV_AZURE_89,CKV_AZURE_98,CKV_AZURE_101,CKV_AZURE_104,CKV_AZURE_106,CKV_AZURE_107,CKV_AZURE_120,CKV_AZURE_121,CKV_AZURE_124,CKV_AZURE_125,CKV2_AZURE_12,CKV2_AZURE_19"
  script:
    - checkov $OPTS -o junitxml | tee checkov_results.xml
    - export TEMPLATE_NAME=".checkov-scan"
  artifacts:
    reports:
      junit: "checkov_results.xml"
    paths:
      - "checkov_results.xml"
    expire_in: 1 week
